### ISSUE TITLE
kanban board

### ISSUE THREAD

**Issue by torobucci** [torobucci/space-travelers#26]
Hello 👋
Here is the [repo link](https://github.com/torobucci/space-travelers)
Here is my [Github Project Link](https://github.com/torobucci/space-travelers/projects/1)

In this react group capstone I had partner issues and was allowed to move on solo.
Here is a screenshot of the message I received.

![Image20230418235532](https://user-images.githubusercontent.com/103370560/232903461-f48caefe-5ff5-486e-af2d-5e4e25d9f7bb.png)

**Comment by brainconnect93** [comment]
### Status: Required Changes ♻️ 

Hello @torobucci,

### To highlight

- SetUp Kanban board ✔️ 

**Changes Required**

- [ ] Having checked your kanban setup, I must commend you have done wonderfully well, But i will like to drop a comment concerning the cards. Currently, i notice that the cards are not assigned at all. As part of the requirement for this milestone, you should assign the cards to your self since you have been permitted to work on a solo. Also kindly check the cards, if you will be implementing the functionality for the 3rd member then you should assign the card but if otherwise you should remove the card and it should not be in your kanban board.

Card details 👇 

![image](https://user-images.githubusercontent.com/78634841/232909111-8dabf6e2-9ad9-45da-9486-d8d96c9087f9.png)


## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by anagudelogu** [comment]
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @torobucci, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of GitHub's project features! 🥇 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
